services:
  - type: web
    name: pawsh
    env: node
    buildCommand: |
      chmod +x render-build.sh
      ./render-build.sh
    staticPublishPath: "./dist"
    envVars:
      - key: NODE_VERSION
        value: 18.x
      - key: NPM_CONFIG_PRODUCTION
        value: "false"
      - key: HOST
        value: "0.0.0.0"
      - key: PORT
        value: "10000"
    startCommand: node /opt/render/project/src/server.js
